Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "jenkins-slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.33.10"  # Adresse IP privée de la deuxième VM

    config.vm.network "forwarded_port", guest: 8080, host: 8002
    config.vm.network "forwarded_port", guest: 22, host: 2202
    slave.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end
	
	config.vm.provision "shell" do |shell|
	  shell.path = "jenkins.sh"
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      usermod -aG docker vagrant
	  sudo sed -i 's/^ExecStart=.*/ExecStart=\/usr\/bin\/dockerd -H tcp:\/\/0.0.0.0:4243 -H unix:\/\/\/var\/run\/docker.sock/g' /lib/systemd/system/docker.service
	  sudo systemctl daemon-reload
	  sudo systemctl restart docker
	  curl http://localhost:4243/version
	  curl http://192.168.33.10:4243/version
    SHELL
  end
end